import { ProjectsSectionType } from '@/lib/types/sections'
import { getId } from '@/lib/utils/helper';


export const projectsSection: ProjectsSectionType = {
    title: 'my projects',
    projects: [
        {
            id: getId(),
            name: 'Need4Need Application',
            url: 'https://github.com/Panchalmeenakshi17/Book-n-Go-Application',
            repo: 'https://github.com/Panchalmeenakshi17/Book-n-Go-Application',
            img: 'https://i.postimg.cc/KYMVfgxr/Whats-App-Image-2024-08-05-at-15-48-56-f112ca34.jpg',
            year: 2024,
            tags: ['React Native', 'Firebase'],
        },
        {
            id: getId(),
            name: 'Book-n-Go Mobile Application',
            url: 'https://github.com/Panchalmeenakshi17/Book-n-Go-Application',
            repo: 'https://github.com/Panchalmeenakshi17/Book-n-Go-Application',
            img: 'https://i.postimg.cc/ZnCz9V2Y/placeholder.png',
            year: 2024,
            tags: ['React Native', 'Firebase'],
        },
    {
        id: getId(),
        name: 'Digihaat',
        url: 'https://digihaat.vercel.app/',
        repo: 'https://github.com/vatsalsinghkv/beautiful-animations',
        img: 'https://i.postimg.cc/VvWPR09H/Screenshot-2024-08-05-154237.png',
        year: 2023,
        tags: [ 'MongoDB','React','Express.js', 'Tailwind'],
    },
    {
        id: getId(),
        name: 'GfG Student Chapter',
        url: 'https://gfgdce2.netlify.app/',
        repo: 'https://github.com/vatsalsinghkv/beautiful-animations',
        img: 'https://i.postimg.cc/hvy46JWv/Screenshot-2024-05-30-003050.png',
        year: 2023,
        tags: [ 'MongoDB','React','Express.js', 'Tailwind'],
    },
    {
        id: getId(),
        name: 'TechPreksha',
        url: 'https://whimsical-bonbon-1cfe60.netlify.app/',
        repo: 'https://github.com/Panchalmeenakshi17/GeeksForGeeks_StudentChapter_WebApp',
        img: 'https://i.postimg.cc/zBwVtXGH/Screenshot-2024-01-10-173739.png',
        year: 2023,
        tags: ['React', 'Tailwind'],
    },
    
    {
        id: getId(),
        name: 'Need4Need - Web Application',
        url: 'https://need4need.netlify.app/',
        repo: 'https://github.com/Panchalmeenakshi17/Need4Need_WebApp',
        img: 'https://i.postimg.cc/FsGQkcHY/Screenshot-2024-08-05-154348.png',
        year: 2023,
        tags: ['MongoDB','React','Express.js', 'Tailwind'],
    },
    {
        id: getId(),
        name: 'Book-n-Go Web-Application',
        url: 'https://github.com/Panchalmeenakshi17/Book-n-Go',
        repo: 'https://github.com/Panchalmeenakshi17/Book-n-Go',
        img: 'https://i.postimg.cc/cJmpXpN4/Screenshot-2024-01-04-122545.png',
        year: 2023-24,
        tags: ['MongoDB','React','Express.js', 'Tailwind'],
    },
    {
        id: getId(),
        name: 'Sanjog',
        url: 'https://github.com/Kunalprajapati1/vivah',
        repo: 'https://github.com/Kunalprajapati1/vivah',
        img: 'https://i.postimg.cc/G3SDTtVq/dd.jpg',
        year: 2024,
        tags: ['React Native', 'Firebase'],
    },
    
    // {
    //     id: getId(),
    //     name: 'weather app',
    //     url: 'https://weather-kv.netlify.app/',
    //     repo: 'https://github.com/Panchalmeenakshi17/weather- pp',
    //     img: 'https://user-images.githubusercontent.com/68834718/148419702-491fa08d-e520-4e2f-b219-374ec7118b2b.png',
    //     year: 2022,
    //     tags: ['Html', 'CSS', 'JS',  ],
    // },
    {
        id: getId(),
        name: 'TurnOnText',
        url: 'https://turnontext.netlify.app/',
        repo: 'https://github.com/Panchalmeenakshi17/TurnOnText',
        img: 'https://i.postimg.cc/rmdZSrYJ/Screenshot-2023-12-17-124510.png',
        year: 2023,
        tags: ['MongoDB','React','Express.js', 'Tailwind' ],
    },
    // {
    //     id: getId(),
    //     name: 'Bharat Cab',
    //     url: 'https://github.com/Panchalmeenakshi17/Real-time-Taxi-BookingApp',
    //     repo: 'https://github.com/Panchalmeenakshi17/Real-time-Taxi-BookingApp',
    //     img: 'https://i.postimg.cc/ZnCz9V2Y/placeholder.png',
    //     year: 2022,
    //     tags: ['Firebase','React-Native'],
    // },
    // {
    //     id: getId(),
    //     name: 'blogr landing page',
    //     url: 'https://blogr-kv.netlify.app/',
    //     repo: 'https://github.com/vatsalsinghkv/blogr-landing-page',
    //     img: 'https://user-images.githubusercontent.com/68834718/210222542-6455303d-c93e-430b-a5c8-96a431044184.png',
    //     year: 2021,
    //     tags: ['html', 'sass', 'JS'],
    // },
    // {
    //     id: getId(),
    //     name: 'natours',
    //     url: 'https://natours-kv.netlify.app/',
    //     repo: 'https://github.com/vatsalsinghkv/natours',
    //     img: 'https://user-images.githubusercontent.com/68834718/210223114-b4f64b44-2501-49c9-9fb7-b8e53fe654c6.png',
    //     year: 2021,
    //     tags: ['html', 'sass', 'JS'],
    // },
    // {
    //     id: getId(),
    //     name: 'nexter',
    //     url: 'https://vatsalsinghkv.github.io/nexter/',
    //     repo: 'https://github.com/vatsalsinghkv/nexter',
    //     img: 'https://user-images.githubusercontent.com/68834718/210224671-5501c5d9-a8d2-4044-a14c-38fb7e46a113.png',
    //     year: 2021,
    //     tags: ['html', 'sass'],
    // },
    // {
    //     id: getId(),
    //     name: 'IP address tracker',
    //     url: 'https://vatsalsinghkv.github.io/ip-address-tracker/',
    //     repo: 'https://github.com/vatsalsinghkv/ip-address-tracker',
    //     img: 'https://user-images.githubusercontent.com/68834718/210223386-03bcaa20-e649-4b3d-8709-59e42c6d685a.png',
    //     year: 2021,
    //     tags: ['html', 'bootstrap', 'JS'],
    // },
    // {
    //     id: getId(),
    //     name: 'calculator app',
    //     url: 'https://vatsalsinghkv.github.io/calculator-app/',
    //     repo: 'https://github.com/vatsalsinghkv/calculator-app/',
    //     img: 'https://user-images.githubusercontent.com/68834718/210223825-3b68d696-39c6-490c-9433-f315b7efccbd.png',
    //     year: 2021,
    //     tags: ['html', 'CSS', 'JS'],
    // },
    // {
    //     id: getId(),
    //     name: 'pig game',
    //     url: 'https://vatsalsinghkv.github.io/pig-game/',
    //     repo: 'https://github.com/vatsalsinghkv/pig-game',
    //     img: 'https://user-images.githubusercontent.com/68834718/210223527-de7fde7a-244e-4db5-8e33-d561afad6084.png',
    //     year: 2021,
    //     tags: ['html', 'CSS', 'JS'],
    // },
    // {
    //     id: getId(),
    //     name: 'bankist marketing',
    //     url: 'https://vatsalsinghkv.github.io/bankist-marketing/',
    //     repo: 'https://github.com/vatsalsinghkv/bankist-marketing',
    //     img: 'https://user-images.githubusercontent.com/68834718/210225545-989f79c3-cf05-4c53-b48e-b21f373b3734.png',
    //     year: 2021,
    //     tags: ['html', 'CSS', 'JS'],
    // },
    ],
};